{% set version = "0.5.1" %}
package:
  name: sphinx_bootstrap_theme
  version: {{ version }}

source:
  url: https://github.com/ryan-roemer/sphinx-bootstrap-theme/archive/v{{ version }}.tar.gz
  fn: sphinx-bootstrap-theme-v{{ version }}.tar.gz
  sha256: b16e0ee97afe142e0b98e33907cf27233dc15c8cdd29fb45e7a55c32df6bfd2a

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - sphinx_bootstrap_theme

about:
  home: http://ryan-roemer.github.com/sphinx-bootstrap-theme/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Sphinx Bootstrap Theme.'
  description: |
      This Sphinx theme integrates the Bootstrap CSS / JavaScript framework
      with various layout options, hierarchical menu navigation, and
      mobile-friendly responsive design. It is configurable, extensible, and
      can use any number of different Bootswatch CSS themes.
  doc_url: http://ryan-roemer.github.io/sphinx-bootstrap-theme/
  dev_url: http://ryan-roemer.github.com/sphinx-bootstrap-theme/

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
